name: Sonar-Build

on: [workflow_dispatch,push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install npm@8
        run: npm i -g npm@8
      - name: Install
        run : |
          npm ci --prefer-offline
          
      - name: Build
        run: |
          npm run build
          npm install --save-dev react-dev-utils
          npm test -- --coverage --watchAll=false
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
